/**
 * SPINdle (version 2.2.4)
 * Copyright (C) 2009-2014 NICTA Ltd.
 *
 * This file is part of SPINdle project.
 * 
 * SPINdle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SPINdle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with SPINdle.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author H.-P. Lam (oleklam@gmail.com), National ICT Australia - Queensland Research Laboratory 
 */
/**
 * Provides implementation of classes for parsing defeasible theory and conclusions represented using DFL.
 * All classes in this package are generated by <a href="http://javacc.java.net/">JavaCC</a>
 * with the specified DFL language.
 * It is going to be used to replace the old DFL theory parser class {@link spindle.io.parser.DflTheoryParser}.
 * 
 * @version Last modified 2012.05.06
 * @since version 2.1.0
 */
package spindle.io.parser.impl;