/**
 * SPINdle (version 2.2.4)
 * Copyright (C) 2009-2014 NICTA Ltd.
 *
 * This file is part of SPINdle project.
 * 
 * SPINdle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SPINdle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with SPINdle.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author H.-P. Lam (oleklam@gmail.com), National ICT Australia - Queensland Research Laboratory 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.05.28 at 11:14:55 AM EST
//
/**
 * Provides implementation classes for parsing defeasible theories and conclusions represented using XML.
 * The classes in this package are generated using <a href="https://jaxb.java.net/">JAXB</a> with the specified XML
 * schema.
 * It is going to be used as the underlying document object model for the new XML theories and conclusions parser (
 * {@link spindle.io.parser.XmlTheoryParser2})
 * and outputter ({@link spindle.io.outputter.XmlTheoryOutputter2}) classes.
 * 
 * @version Last modified 2012.05.28
 * @since version 2.2.2
 * @see spindle.io.parser.XmlTheoryParser
 * @see spindle.io.outputter.XmlTheoryOutputter
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://spin.nicta.org.au/spindle/spindleDefeasibleTheory2.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package spindle.io.xjc.dom2;

