/**
 * SPINdle (version 2.2.4)
 * Copyright (C) 2009-2014 NICTA Ltd.
 *
 * This file is part of SPINdle project.
 * 
 * SPINdle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SPINdle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with SPINdle.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author H.-P. Lam (oleklam@gmail.com), National ICT Australia - Queensland Research Laboratory 
 */
package spindle.sys.message;

/**
 * System message constants.
 * 
 * @author H.-P. Lam (oleklam@gmail.com), National ICT Australia - Queensland Research Laboratory
 * @since version 1.0.0
 */
public interface SystemMessage {

	// System
	String SYSTEM_LOCALE = "SYSTEM_LOCALE";

	String APPLICATION_TEXT_START = "APPLICATION_TEXT_START";
	String APPLICATION_TEXT_END = "APPLICATION_TEXT_END";

	String APPLICATION_CONTEXT_INITIALIZE_START = "APPLICATION_CONTEXT_INITIALIZE_START";
	String APPLICATION_CONTEXT_INITIALIZE_END = "APPLICATION_CONTEXT_INITIALIZE_END";
	String APPLICATION_CONTEXT_TERMINATE_START = "APPLICATION_CONTEXT_TERMINATE_START";
	String APPLICATION_CONTEXT_TERMINATE_END = "APPLICATION_CONTEXT_TERMINATE_END";
	String APPLICATION_CALLING_SHUTDOWN_ROUTINE = "APPLICATION_CALLING_SHUTDOWN_ROUTINE";
	String APPLICATION_NO_THEORY_TO_PROCESS = "APPLICATION_NO_THEORY_TO_PROCESS";
	String APPLICATION_OPERATION_SUCCESS = "APPLICATION_OPERATION_SUCCESS";
	String APPLICATION_OPERATION_FAILED = "APPLICATION_OPERATION_FAILED";

	// I/O
	String IO_LOAD_THEORY_FROM_FILE = "IO_LOAD_THEORY_FROM_FILE";
	String IO_LOAD_THEORY_FROM_URL = "IO_LOAD_THEORY_FROM_URL";
	String IO_LOAD_THEORY_FROM_XML_STRING = "IO_LOAD_THEORY_FROM_XML_STRING";
	String IO_LOAD_THEORY_FROM_DFL_STRING = "IO_LOAD_THEORY_FROM_DFL_STRING";
	String IO_SAVE_THEORY = "IO_SAVE_THEORY";
	String IO_SAVE_CONCLUSIONS = "IO_SAVE_CONCLUSIONS";
	String IO_OVERWRITE_EXISTING_FILE = "IO_OVERWRITE_EXISTING_FILE";

	// theory
	String THEORY_THEORY_CONTAINS = "THEORY_THEORY_CONTAINS";
	String THEORY_NEW_THEORY = "THEORY_NEW_THEORY";
	String THEORY_ADD_NEW_FACT = "THEORY_ADD_NEW_FACT";
	String THEORY_ADD_NEW_RULE = "THEORY_ADD_NEW_RULE";
	String THEORY_ADD_NEW_DEFEATER = "THEORY_ADD_NEW_DEFEATER";
	String THEORY_ADD_NEW_SUPERIORITY_RELATION = "THEORY_ADD_NEW_SUPERIORITY_RELATION";
	String THEORY_ADD_NEW_MODE_CONVERSION_RULE = "THEORY_ADD_NEW_MODE_CONVERSION_RULE";
	String THEORY_ADD_NEW_MODE_CONFLICT_RULE = "THEORY_ADD_NEW_MODE_CONFLICT_RULE";
	String THEORY_ADD_NEW_LITERAL_VARIABLE = "THEORY_ADD_NEW_LITERAL_VARIABLE";
	String THEORY_REPLACE_RULE_IN_THEORY = "THEORY_REPLACE_RULE_IN_THEORY";
	String THEORY_CONTAINS_NO_LITERAL_VARIABLES = "THEORY_CONTAINS_NO_LITERAL_VARIABLES";
	String THEORY_CONTAINS_NO_SUPERIORITY = "THEORY_CONTAINS_NO_SUPERIORITY";
	String THEORY_CONTAINS_NO_DEFEATER = "THEORY_CONTAINS_NO_DEFEATER";
	String THEORY_CONTAINS_NO_FACT_OR_STRICT_RULES = "THEORY_CONTAINS_NO_FACT_OR_STRICT_RULES";

	// reasoner
	String REASONER_THEORY_LOADED_SUCCESSFULLY = "REASONER_THEORY_LOADED_SUCCESSFULLY";
	String REASONER_GENERATE_CONCLUSIONS = "REASONER_GENERATE_CONCLUSIONS";
	String REASONER_CONCLUSIONS_GENERATED = "REASONER_CONCLUSIONS_GENERATED";
	String REASONER_GET_CONCLUSION_AS_SET = "REASONER_GET_CONCLUSION_AS_SET";
	String REASONER_TIME_USED = "REASONER_TIME_USED";

	// theory normalizer
	String THEORY_NORMALIZER_REGULAR_FORM_TRANSFORMATION = "THEORY_NORMALIZER_REGULAR_FORM_TRANSFORMATION";
	String THEORY_NORMALIZER_PLAIN_AND_TEMPORAL_FORM_OF_SAME_LITERAL_APPEAR_IN_CONFLICTING_HEADS = "THEORY_NORMALIZER_PLAIN_AND_TEMPORAL_FORM_OF_SAME_LITERAL_APPEAR_IN_CONFLICTING_HEADS";

	// reasoning engine
	String REASONING_ENGINE_INITIALIZE_START = "REASONING_ENGINE_INITIALIZE_START";
	String REASONING_ENGINE_INITIALIZE_END = "REASONING_ENGINE_INITIALIZE_END";
	String REASONING_ENGINE_REMOVE_SUPERIORITY_FROM_THEORY = "REASONING_ENGINE_REMOVE_SUPERIORITY_FROM_THEORY";
	String REASONING_ENGINE_REMOVE_DEFEATER_FROM_THEORY = "REASONING_ENGINE_REMOVE_DEFEATER_FROM_THEORY";
	String REASONING_ENGINE_CONCLUSIONS_GENERATION_START = "REASONING_ENGINE_CONCLUSIONS_GENERATION_START";
	String REASONING_ENGINE_CONCLUSIONS_GENERATION_END = "REASONING_ENGINE_CONCLUSIONS_GENERATION_END";
	String REASONING_ENGINE_TERMINATE_START = "REASONING_ENGINE_TERMINATE_START";
	String REASONING_ENGINE_TERMINATE_END = "REASONING_ENGINE_TERMINATE_END";
	String REASONING_ENGINE_ALL_PENDING_CONCLUSIONS_ARE_EVALUATED = "REASONING_ENGINE_ALL_PENDING_CONCLUSIONS_ARE_EVALUATED";

	// console
	String CONSOLE_CONSOLE_MODE_START = "CONSOLE_CONSOLE_MODE_START";
	String CONSOLE_CONSOLE_MODE_TERMINATE = "CONSOLE_CONSOLE_MODE_TERMINATE";
	String CONSOLE_COMMANDS_COMMAND = "CONSOLE_COMMANDS_COMMAND";
	String CONSOLE_COMMANDS_DESCRIPTION = "CONSOLE_COMMANDS_DESCRIPTION";
	String CONSOLE_SHOW_COMMAND_MANUAL = "CONSOLE_SHOW_COMMAND_MANUAL";
	String CONSOLE_CLEAR_SYSTEM_ENVIRONMENT = "CONSOLE_CLEAR_SYSTEM_ENVIRONMENT";
	String CONSOLE_ADD_MODE_CONVERSION_RULE = "CONSOLE_ADD_MODE_CONVERSION_RULE";
	String CONSOLE_ADD_MODE_CONFLICT_RULE = "CONSOLE_ADD_MODE_CONFLICT_RULE";
}
